### ISSUE TITLE
I want to modify the navbar 

### ISSUE THREAD

**Issue by jaswalsaurabh** [loklak/wp-tweetscroll-widget#19]
The sticky navbar is not looking great in mid of the page because the colour of navbar and section of the container is same and also there is some overlapping of the text while scrolling.
![Screenshot (125)](https://user-images.githubusercontent.com/70649392/97139847-63f2ab00-1781-11eb-9afd-235820822f85.png)

**Comment by jaswalsaurabh** [comment]
Can I work on this?

**Comment by chehak123** [comment]
Can i work on this issue?

**Comment by sanjug-sonowal** [comment]
I am happy to do this work , can i implement my design to this?

**Comment by JayJoshi802** [comment]
Hello, I am new to open source. I want to work on it and contribute to it and by doing so I will also get some experience and get familiar with open source. Can I work on this?

**Comment by priyanshu1909** [comment]
hello can i work on this?

**Comment by akashthedeveloper** [comment]
Should I fix this issue
