### ISSUE TITLE
[Feature request] Dark Mode

### ISSUE THREAD

**Issue by Harshal0902** [loklak/wp-tweetscroll-widget#21]

**Comment by Harshal0902** [comment]
Can I work on this issue?

**Comment by Vineet955** [comment]
hello @Harshal0902 , Can i work on this issue,please?

**Comment by JayJoshi802** [comment]
Hello,I am new to open source.I want to work on it and contribute to it and by doing so I will also get some experience and get familiar with open source. Can I work on this?

**Comment by Rashika101** [comment]
Hey!! are you willing to accept new contributors? I am interested into contributing to this repository so, if you could explain a bit more this feature request, it would be great.
Thanks
