### ISSUE TITLE
Want to change the year

### ISSUE THREAD

**Issue by 123mansha** [loklak/wp-tweetscroll-widget#22]
[
![Screenshot 2020-12-05 233016](https://user-images.githubusercontent.com/59260493/101259917-fe1b1b00-3751-11eb-82e8-137974dd267d.jpg)
](url)

**Comment by 123mansha** [comment]
can I work on this??

**Comment by JayJoshi802** [comment]
I am new to GitHub and i am exploring things.I am new to open source.I want to work on this and contribute something and by doing so I will also get to learn something
